version: "3.8"

services:
  ollama:
    build:
      context: .
    container_name: ollama
    networks:
      - mono-network
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    command: >
      bash -c "
        ollama serve & 
        sleep 5 && 
        ollama pull deepseek-r1:1.5b && 
        ollama pull bge-m3 && 
        wait
      "
    tty: true
    stdin_open: true

networks:
  mono-network:
    external: true

volumes:
  ollama-data:
